* Org Mode Guide

** Intro
   This is only an introductory guide. Some of the content in this guide came from the Org[fn:1] website.

** Headlines
   By default, headlines have to start on the left margin and are collapsable with tab

** Lists
   - Unordered list items start with '-', '+', or '*' as bullets
   - Ordered list items start with '1.' or '1)'
   - Description list use '::' (with a space before and after) to seperate the term from the description
*** Lord of the Rings
    My favorite scenes are (in this order)
    1. The attack of the Rohirrim
    2. Eowyn's fight with the witch king
       + this was already my favorite scene in the book
       + I really like Miranda Otto.
    Important actors in this film are:
    - Elijah Wood :: He plays Frodo
    - Sean Astin :: He plays Sam, Frodo's friend.

** To-Do's
   Any headline becomes a TODO item when it starts with the word TODO
*** TODO Write this Org mode guide!
    You can cycle through the state of the TODO item with C-c C-t

    #+BEGIN_EXAMPLE
    ,-> (unmarked) -> TODO -> DONE --.
    `--------------------------------`
    #+END_EXAMPLE

** Checkboxes
   Toggle checkboxes with C-c C-c. Append checkbox with a number over another number to keep track of how many tasks are completed.
*** TODO Organize party [2/4]
    - [-] call people [1/3]
      - [ ] Peter
      - [X] Sarah
      - [ ] Sam
    - [X] order food
    - [ ] think about what music to play
    - [X] talk to neighbors

** Source Code
   Put your cursor in the code block below and do C-c C-c to see what happens!
   #+BEGIN_SRC emacs-lisp
     (+ 1 2 3 4)
   #+END_SRC

** Exporting
   C-c C-e will bring up the export manager

[fn:1] The link is: https://orgmode.org
