#+TITLE: Org Mode Guide
#+AUTHOR: Palmer Cluff

* Org Mode Guide

** Intro
   This is only an introductory guide. Some of the content in this guide came from the Org[fn:1] website.

** Headlines
   By default, headlines have to start on the left margin and are collapsable with tab

** Paragraphs
   This is a paragraph. I can continue writing on this line.
   Or this line. And it will be within the same paragraph.

   An empty line seperating two sentence blocks will breate a new paragraph.
   I can also force\\
   A new line. Or
   -----
   A horizontal line.

*** Poetry
    #+BEGIN_VERSE
    Great clouds overhead
    Tiny black birds rise and fall
    Snow covers Emacs

         -- AlexSchroeder
    #+END_VERSE

*** Quotes
    #+BEGIN_QUOTE
    Everything should be made as simple as possible,
    but not any simpler -- Albert Einstein
    #+END_QUOTE

*** Centered Text
    #+BEGIN_CENTER
    Everything should be made as simple as possible, \\
    but not any simpler
    #+END_CENTER

** Emphasis and Monospace
   You can make words *bold*, /italic/, _underlined_, =verbatim=, ~code~, and +strike-through+.

** Tables
   |Name|Phone|Age|
   |-

   Pushing tab after =|-= will produce this:
   | Name | Phone | Age |
   |------+-------+-----|
   |      |       |     |

   And that in turn will allow to fill out the rest of the fields. Use tab to cycle through.
   | Name         | Phone | Age |
   |--------------+-------+-----|
   | John         |  1234 |  21 |
   | Jane         |  5678 |  21 |
   | Palmer Cluff |  1234 |  21 |

** Lists
   - Unordered list items start with '-', '+', or '*' as bullets
   - Ordered list items start with '1.' or '1)'
   - Description list use '::' (with a space before and after) to seperate the term from the description
*** Lord of the Rings
    My favorite scenes are (in this order)
    1. The attack of the Rohirrim
    2. Eowyn's fight with the witch king
       + this was already my favorite scene in the book
       + I really like Miranda Otto.
    Important actors in this film are:
    - Elijah Wood :: He plays Frodo
    - Sean Astin :: He plays Sam, Frodo's friend.

** To-Do's
   Any headline becomes a TODO item when it starts with the word TODO
*** TODO Write this Org mode guide!
    You can cycle through the state of the TODO item with C-c C-t

    #+BEGIN_EXAMPLE
    ,-> (unmarked) -> TODO -> DONE --.
    `--------------------------------`
    #+END_EXAMPLE

** Checkboxes
   Toggle checkboxes with C-c C-c. Append checkbox with a number over another number to keep track of how many tasks are completed.
*** TODO Organize party [2/4]
    - [-] call people [1/3]
      - [ ] Peter
      - [X] Sarah
      - [ ] Sam
    - [X] order food
    - [ ] think about what music to play
    - [X] talk to neighbors

** Source Code
   Put your cursor in the code block below and do C-c C-c to see what happens!
   #+BEGIN_SRC emacs-lisp
     (+ 1 2 3 4)
   #+END_SRC

** Exporting
   C-c C-e will bring up the export manager

[fn:1] The link is: https://orgmode.org
